language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test it:test
scala:
  - 2.13.4
  - 2.12.11
  - 2.11.12
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
addons:
  postgresql: 10
notifications:
  email:
    - martins@uniso.lv
